### ISSUE TITLE
您好，我我问一个webpack4 ，代码分割的问题看我截图

### ISSUE THREAD

**Issue by liuxiaobina** [BUPTlhuanyu/react-music-lhy#3]
ERROR in C:\Users\Administrator\Desktop\webpack4\src\index.tsx(11,1)
      TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

//////////////////////////////////////////////////

const NotFound = Loadable({
  loading,
  loader: () => {return import(/* webpackChunkName: "NotFound" */"../pages/NotFound")}
});

使用时这样的，好像是我webpack 配置的问题
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": ["types/*"]
        },
        "jsx": "react",
        "lib": ["esnext",  "dom.iterable","dom"],
        "rootDir": "src",
        "module": "esnext",
        "target": "es5",
        "sourceMap": true,
        "moduleResolution": "node",
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "experimentalDecorators": true,
        "allowJs": true,
    },
    "files": [
        "images.d.ts"
    ],
    "include": [
        "./src/*"
    ],
    "exclude": [
        "build"
    ],
    "noImplicitAny": false
}我应该怎么改，我扣扣2385943935，请赐教

**Comment by BUPTlhuanyu** [comment]
如果是用高版本的react，那么建议你使用react.lazy，此项目中用的react-loadable，但是存在一些bug，在本项目的app.tsx文件中，我所有的懒加载组件导入逻辑都放到了整个文件的export后面了。这也是我的一个疑惑的问题，暂时没有找到是为何原因。话说回来，您说到的问题，我也无法准确的定位到问题的所在，如果是import不能作为方法使用的问题，建议先用单独用import()试一下，看能否编译通过。
